version: 1

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
    - echo Building the Docker image...
    - docker build -t coworking-analytics
    - docker tag coworking-analytics:latest 451924012152.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 451924012152.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:latest