version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase complete"
  build:
    commands:
      - echo "Build phase complete"
  post_build:
    commands:
      - echo "Post-build phase complete"